name: Scrape Latest Anime Episodes

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Run scraper
        run: python -u scraper.py

      - name: Commit and push changes
        run: |
          # Hanya jalankan jika file database ada
          if [ ! -f anime_database.json ]; then
            echo "anime_database.json not found. Skipping commit."
            exit 0
          fi
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add anime_database.json
          # Hanya commit jika ada perubahan
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update anime database" -a
          fi
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
